# code: language=ansible
---
- name: Install dconf (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - dconf-cli
      - dconf-editor
  when: ansible_facts['os_family'] == "Debian"

- name: Install dconf (RedHat/CentOS)
  ansible.builtin.dnf:
    name:
      - dconf
      - dconf-editor
  when: ansible_facts['os_family'] == "RedHat"
   
# To review dconf settings, install the graphical dconf Editor.
- name: Install the 'user' dconf profile
  ansible.builtin.copy:
    src: user
    dest: /etc/dconf/profile/user
    owner: root
    group: root
    mode: 0644

- name: Create dconf 'local' db directories
  ansible.builtin.file:
    path: "{{ dconf_db_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/dconf/db/local.d
    - /etc/dconf/db/local.d/locks
  loop_control:
    loop_var: dconf_db_dir

- name: Copy dconf key settings files
  ansible.builtin.copy:
    src: "{{ dconf_keyfile }}"
    dest: "/etc/dconf/db/local.d/{{ dconf_keyfile | basename }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ query('ansible.builtin.fileglob', role_path ~ '/files/keyfiles/*') }}"
  loop_control:
    loop_var: dconf_keyfile
  notify: Update dconf databases

- name: Copy dconf lock files
  ansible.builtin.copy:
    src: "{{ dconf_lockfile }}"
    dest: "/etc/dconf/db/local.d/locks/{{ dconf_lockfile | basename }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ query('ansible.builtin.fileglob', role_path ~ '/files/lockfiles/*') }}"
  loop_control:
    loop_var: dconf_lockfile
  notify: Update dconf databases
