# code: language=ansible
---
- name: Install GUI packages
  ansible.builtin.package:
    name:
      - gcompris-qt
      - gcompris-qt-data
      - ktuberling
      - tuxpaint
      - tuxpaint-data

- name: Install Firefox
  ansible.builtin.apt:
    name: firefox
  when: firefox_install | bool

- name: Uninstall Firefox
  ansible.builtin.apt:
    name: firefox
    state: absent
  when: not (firefox_install | bool)
