# code: language=ansible
---
- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release

- name: Install flatpak
  ansible.builtin.dnf:
    name: flatpak

- name: Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install required RedHat GUI packages
  ansible.builtin.package:
    name:
      - ktuberling
    state: present
  when: ansible_facts['virtualization_type'] is not defined or ansible_facts['virtualization_type'] not in ['docker', 'containerd', 'podman']

- name: Install GUI applications via Flatpak
  community.general.flatpak:
    name:
      - org.gnome.GCompris
      - net.sourceforge.TuxPaint
    state: present
    method: system
    remote: flathub
  when: ansible_facts['virtualization_type'] is not defined or ansible_facts['virtualization_type'] not in ['docker', 'containerd', 'podman']

- name: Install Firefox
  ansible.builtin.dnf:
    name: firefox
  when: firefox_install | bool

- name: Uninstall Firefox
  ansible.builtin.dnf:
    name: firefox
    state: absent
  when: not (firefox_install | bool)
