# code: language=ansible
---
- name: Gather service facts for network handlers
  ansible.builtin.service_facts:
  changed_when: false
  failed_when: false  # Don't fail under Docker without systemd etc.

- name: Include task list appropriate for OS family (Debian/RedHat)
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Override DHCP DNS servers (Debian)
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhclient.conf
    create: true
    regexp: "^supersede domain-name-servers"
    line: "supersede domain-name-servers {{ dns_servers | join(',') }};"
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['os_family'] == "Debian"
