---
- name: Disable NetworkManager DNS configuration
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none
    no_extra_spaces: yes
    mode: "0644"
  notify: Restart NetworkManager
  when:
    - ansible_facts['virtualization_type'] is not defined or ansible_facts['virtualization_type'] not in ['docker', 'containerd', 'podman']

# We need NetworkManager to restart before we attempt to change resolv.conf
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  when:
    - ansible_facts['virtualization_type'] is not defined or ansible_facts['virtualization_type'] not in ['docker', 'containerd', 'podman']

- name: Configure DNS settings
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_facts['virtualization_type'] is not defined or ansible_facts['virtualization_type'] not in ['docker', 'containerd', 'podman']

- name: Skip resolv.conf override in containerized environments
  ansible.builtin.debug:
    msg: >
      Skipping direct /etc/resolv.conf management in containerized tests where
      the file is Docker-managed.
  when:
    - ansible_facts['virtualization_type'] is defined
    - ansible_facts['virtualization_type'] in ['docker', 'containerd', 'podman']
  
