# code: language=ansible
---
## ESSENTIALS

- name: Install ufw
  ansible.builtin.package:
    name: ufw
  notify: Start ufw

- name: Allow SSH through firewall
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Enable ufw
  community.general.ufw:
    state: enabled

## ALL OTHER RULES

# - name: Allow HTTP and HTTPS through firewall
#   ansible.builtin.ufw:
#     rule: allow
#     port: "{{ item }}"
#   loop: [http, https]
