---
- name: Converge
  hosts: all
  vars_files:
    - "../../../config.yml"
  vars:
    _molecule_clear_proxy_env: "{{ molecule_clear_proxy_env | default(false) | bool }}"
    _molecule_clear_proxy_env_vars:
      http_proxy: ""
      https_proxy: ""
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      no_proxy: ""
      NO_PROXY: ""
  environment: "{{ _molecule_clear_proxy_env_vars if _molecule_clear_proxy_env else {} }}"
  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      become: true
      when: ansible_facts['os_family'] == "Debian"
    - name: update yum cache
      ansible.builtin.yum:
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == "RedHat"
  roles:
    - {role: "dconf", become: true}
    - {role: "firewall", become: true}
    - {role: "gnome", become: true}
    - {role: "gui_packages", become: true}
    - {role: "name", become: true}
    - {role: "network", become: true}
    - {role: "packages", become: true}
    - {role: "plymouth", become: true}
    - {role: "proxy", become: true}
    - {role: "selinux", become: true}
    - {role: "user", become: true}
    - {role: "version", become: true}
