---
- name: Prepare
  hosts: all
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    no_proxy: ""
    NO_PROXY: ""
  tasks:
    - name: install Gnome & dconf
      ansible.builtin.apt:
        name: [
          "gnome-core",
          "dconf-cli",
          "dconf-editor",
        ]
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: install dconf tools (RedHat)
      ansible.builtin.dnf:
        name: [
          "dconf",
          "dconf-editor",
        ]
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'RedHat'
