---
- name: Prepare
  hosts: all
  vars:
    molecule_clear_proxy_env: "{{ molecule_clear_proxy_env | default(false) | bool }}"
  environment:
    http_proxy: "{{ '' if molecule_clear_proxy_env else omit }}"
    https_proxy: "{{ '' if molecule_clear_proxy_env else omit }}"
    HTTP_PROXY: "{{ '' if molecule_clear_proxy_env else omit }}"
    HTTPS_PROXY: "{{ '' if molecule_clear_proxy_env else omit }}"
    no_proxy: "{{ '' if molecule_clear_proxy_env else omit }}"
    NO_PROXY: "{{ '' if molecule_clear_proxy_env else omit }}"
  tasks:
    - name: install Gnome & dconf
      ansible.builtin.apt:
        name: [
          "gnome-core",
          "dconf-cli",
          "dconf-editor",
        ]
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: install dconf tools (RedHat)
      ansible.builtin.dnf:
        name: [
          "dconf",
          "dconf-editor",
        ]
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'RedHat'
