---
- name: Prepare
  hosts: all
  vars:
    _molecule_clear_proxy_env: "{{ molecule_clear_proxy_env | default(false) | bool }}"
    _molecule_clear_proxy_env_vars:
      http_proxy: ""
      https_proxy: ""
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      no_proxy: ""
      NO_PROXY: ""
  environment: "{{ _molecule_clear_proxy_env_vars if _molecule_clear_proxy_env else {} }}"
  tasks:
    - name: Install Gnome & dconf
      ansible.builtin.apt:
        name: [
          "gnome-core",
          "dconf-cli",
          "dconf-editor",
        ]
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install dconf tools (RedHat)
      ansible.builtin.dnf:
        name: [
          "dconf",
          "dconf-editor",
        ]
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'RedHat'
