# code: language=ansible
---
- name: Install default Plymouth splash screen
  ansible.builtin.apt:
    name: plymouth-theme-spinner
  notify:
    - "Plymouth tasks"
  when: ansible_facts['os_family'] == "Debian"
